services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Pintushi\Bundle\SearchBundle\:
        resource: '../../{Repository,DataFixtures,Command,Validator,Controller}'

    pintushi_search.index:
        alias: Pintushi\Bundle\SearchBundle\Engine\Indexer

    Pintushi\Bundle\SearchBundle\Engine\Indexer:
        arguments:
            - '@pintushi_search.search.engine'
            - '@pintushi_search.mapper'
            - '@Pintushi\Bundle\SearchBundle\Security\SecurityProvider'
            - '@Pintushi\Bundle\SearchBundle\Utils\AclHelper'
            - '@event_dispatcher'

    Pintushi\Bundle\SearchBundle\Security\SecurityProvider:
        public:  false
        arguments:
            - "@security.authorization_checker"
            - "@pintushi_security.entity_security_metadata_provider"

    pintushi_search.mapper:
        class: 'Pintushi\Bundle\SearchBundle\Engine\ObjectMapper'
        arguments: ['@event_dispatcher']
        calls:
            - [setMappingProvider, ['@Pintushi\Bundle\SearchBundle\Provider\SearchMappingProvider']]
            - [setPropertyAccessor, ['@property_accessor']]

    Pintushi\Bundle\SearchBundle\Utils\AclHelper:
        arguments:
            - '@Pintushi\Bundle\SearchBundle\Provider\SearchMappingProvider'
            - '@pintushi_security.token_accessor'
            - '@pintushi_security.orm.ownership_sql_walker_builder'
            - '@pintushi_security.owner.ownership_metadata_provider.chain'

    Pintushi\Bundle\SearchBundle\Provider\SearchMappingProvider:
        arguments:
            - '@event_dispatcher'
            - '@pintushi_search.cache.mapping_configuration'

    pintushi_search.cache.mapping_configuration:
        public: false
        autowire: false
        autoconfigure: false
        parent: doctrine_cache.abstract.chain
        calls:
            - [ setNamespace, [ 'pintushi_search_mapping_configuration' ] ]
