services:
    pintushi_search.search.engine:
        class: Pintushi\Bundle\SearchBundle\Engine\Orm
        arguments:
            - '@doctrine'
            - '@pintushi_search.mapper'
            - '@event_dispatcher'
        calls:
            - [setLogQueries, ['%pintushi_search.log_queries%']]

    pintushi_search.search.engine.indexer:
        class: Pintushi\Bundle\SearchBundle\Engine\OrmIndexer
        public: true
        arguments:
            - '@doctrine'
            - '@Pintushi\Bundle\SecurityBundle\ORM\DoctrineHelper'
            - '@pintushi_search.mapper'
            - '@Pintushi\Bundle\EntityBundle\Provider\EntityNameResolver'
